# 🐼 Python Pandas Comprehensive Tutorial

This notebook covers the fundamental and advanced features of the Pandas library with hands-on examples.

## Table of Contents
1. Introduction to Pandas
2. Series
3. Creating DataFrames
4. Reading / Writing Data
5. Exploring Data
6. Data Selection & Indexing
7. Data Filtering
8. Data Cleaning
9. Data Transformation
10. Grouping & Aggregation
11. Joining & Merging
12. Time Series
13. Exercises & Answers

In [1]:
import pandas as pd
import numpy as np

print(f"Pandas version: {pd.__version__}")
print(f"NumPy version: {np.__version__}")

Pandas version: 2.0.3
NumPy version: 1.24.3

---
## 1. 📊 Series

A `Series` is a one-dimensional labeled data structure. Think of it like a list, but every element has an index (label).

In [2]:
# Creating a Series from a list
s1 = pd.Series([10, 20, 30, 40, 50])
print("Series from list:")
print(s1)
print(f"\nType: {s1.dtype}, Shape: {s1.shape}")

Series from list:
0    10
1    20
2    30
3    40
4    50
dtype: int64

Type: int64, Shape: (5,)

In [3]:
# Series with custom index
s2 = pd.Series([23.5, 18.0, 31.2, 27.8],
               index=['January', 'February', 'March', 'April'],
               name='Average Temperature (°C)')
print(s2)
print(f"\nMarch temperature: {s2['March']}°C")

January     23.5
February    18.0
March       31.2
April       27.8
Name: Average Temperature (°C), dtype: float64

March temperature: 31.2°C

In [4]:
# Series from a dictionary
s3 = pd.Series({'Apple': 5, 'Banana': 3, 'Orange': 8, 'Strawberry': 12})
print("Series from dictionary:")
print(s3)

# Mathematical operation on a Series
print("\nDoubled:")
print(s3 * 2)

Series from dictionary:
Apple          5
Banana         3
Orange         8
Strawberry    12
dtype: int64

Doubled:
Apple         10
Banana         6
Orange        16
Strawberry    24
dtype: int64

In [9]:
(s3*2)['Apple']
s3['Apple']

10

---
## 2. 📋 Creating DataFrames

A `DataFrame` is a two-dimensional labeled data structure. Think of it like an Excel spreadsheet.

In [10]:
# DataFrame from a dictionary
df_student = pd.DataFrame({
    'Name': ['Ali', 'Ayse', 'Mehmet', 'Fatma', 'Can'],
    'Age': [20, 22, 21, 23, 19],
    'Grade': [85, 92, 78, 95, 88],
    'City': ['Istanbul', 'Ankara', 'Izmir', 'Istanbul', 'Bursa']
})
print("Student DataFrame:")
df_student

Student DataFrame:

     Name  Age  Grade      City
0     Ali   20     85  Istanbul
1    Ayse   22     92    Ankara
2  Mehmet   21     78     Izmir
3   Fatma   23     95  Istanbul
4     Can   19     88     Bursa

In [11]:
# DataFrame from a list of lists
data = [
    ['Laptop', 15000, 'Electronics'],
    ['Desk', 2500, 'Furniture'],
    ['Phone', 8000, 'Electronics'],
    ['Chair', 1200, 'Furniture'],
]
df_product = pd.DataFrame(data, columns=['Product', 'Price', 'Category'])
print("Product DataFrame:")
df_product

Product DataFrame:

  Product  Price     Category
0  Laptop  15000  Electronics
1    Desk   2500    Furniture
2   Phone   8000  Electronics
3   Chair   1200    Furniture

In [15]:
# Large DataFrame using NumPy
np.random.seed(42)
df_large = pd.DataFrame(
    np.random.randn(100, 4),
    columns=['A', 'B', 'C', 'D']
)
print(f"Shape: {df_large.shape}")
df_large.tail(10)

Shape: (100, 4)

           A         B         C         D
90  0.519347  1.532739 -0.108760  0.401712
91  0.690144 -0.401220  0.224092  0.012592
92  0.097676 -0.773010  0.024510  0.497998
93  1.451144  0.959271  2.153182 -0.767348
94  0.872321  0.183342  2.189803 -0.808298
95 -0.839722 -0.599393 -2.123896 -0.525755
96 -0.759133  0.150394  0.341756  1.876171
97  0.950424 -0.576904 -0.898415  0.491919
98 -1.320233  1.831459  1.179440 -0.469176
99 -1.713135  1.353872 -0.114540  1.237816

---
## 3. 🔍 Exploring Data

Essential methods for understanding your data.

In [16]:
# Build a sample dataset
np.random.seed(0)
df = pd.DataFrame({
    'name': ['Ali', 'Ayse', 'Mehmet', 'Fatma', 'Can', 'Zeynep', 'Hasan', 'Merve'],
    'age': [25, 30, 35, 28, 22, 33, 27, 29],
    'salary': [5000, 7500, 9000, 6500, 4500, 8000, 5500, 7000],
    'department': ['IT', 'HR', 'IT', 'Finance', 'IT', 'HR', 'Finance', 'IT'],
    'experience': [2, 5, 10, 4, 1, 8, 3, 6]
})

print("First 5 rows (head):")
print(df.head())

First 5 rows (head):
     name  age  salary department  experience
0     Ali   25    5000         IT           2
1    Ayse   30    7500         HR           5
2  Mehmet   35    9000         IT          10
3   Fatma   28    6500    Finance           4
4     Can   22    4500         IT           1

In [17]:
print("Last 3 rows (tail):")
print(df.tail(3))

Last 3 rows (tail):
     name  age  salary department  experience
5  Zeynep   33    8000         HR           8
6   Hasan   27    5500    Finance           3
7   Merve   29    7000         IT           6

In [18]:
print("General info (info):")
df.info()

General info (info):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        8 non-null      object
 1   age         8 non-null      int64
 2   salary      8 non-null      int64
 3   department  8 non-null      object
 4   experience  8 non-null      int64
dtypes: int64(3), object(2)
memory usage: 448.0+ bytes

In [19]:
print("Statistical summary (describe):")
df.describe()

Statistical summary (describe):

             age       salary  experience
count   8.000000     8.000000    8.000000
mean   28.625000  6625.000000    4.875000
std     4.172615  1552.647509    3.044316
min    22.000000  4500.000000    1.000000
25%    26.500000  5375.000000    2.750000
50%    28.500000  6750.000000    4.500000
75%    30.750000  7625.000000    6.500000
max    35.000000  9000.000000   10.000000

In [20]:
print(f"Shape: {df.shape}")
print(f"Columns: {list(df.columns)}")
print(f"Index: {list(df.index)}")
print(f"\nData types:")
print(df.dtypes)

Shape: (8, 5)
Columns: ['name', 'age', 'salary', 'department', 'experience']
Index: [0, 1, 2, 3, 4, 5, 6, 7]

Data types:
name          object
age            int64
salary         int64
department    object
experience     int64
dtype: object

In [21]:
# value_counts - count category occurrences
print("Department distribution:")
print(df['department'].value_counts())

Department distribution:
department
IT         4
HR         2
Finance    2
Name: count, dtype: int64

---
## 4. 🎯 Data Selection & Indexing

Methods for accessing specific rows and columns.

In [22]:
# Single column selection
print("Names (single column):")
print(df['name'])

Names (single column):
0       Ali
1      Ayse
2    Mehmet
3     Fatma
4       Can
5    Zeynep
6     Hasan
7     Merve
Name: name, dtype: object

In [23]:
# Multiple column selection
print("Name and Salary:")
print(df[['name', 'salary']])

Name and Salary:
     name  salary
0     Ali    5000
1    Ayse    7500
2  Mehmet    9000
3   Fatma    6500
4     Can    4500
5  Zeynep    8000
6   Hasan    5500
7   Merve    7000

In [24]:
# .loc - Label-based selection
print(".loc row selection (index 2):")
print(df.loc[2])

print("\n.loc row and column selection:")
print(df.loc[1:3, ['name', 'salary', 'department']])

.loc row selection (index 2):
name          Mehmet
age               35
salary          9000
department        IT
experience        10
Name: 2, dtype: object

.loc row and column selection:
     name  salary department
1    Ayse    7500         HR
2  Mehmet    9000         IT
3   Fatma    6500    Finance

In [25]:
# .iloc - Position-based selection
print(".iloc first 3 rows, first 2 columns:")
print(df.iloc[:3, :2])

print("\n.iloc specific cell (row 0, column 2):")
print(df.iloc[0, 2])

.iloc first 3 rows, first 2 columns:
     name  age
0     Ali   25
1    Ayse   30
2  Mehmet   35

.iloc specific cell (row 0, column 2):
5000

In [ ]:
# at and iat - fast single-cell access
print(f".at access (index 3, 'name'): {df.at[3, 'name']}")
print(f".iat access (row 3, column 0): {df.iat[3, 0]}")

---
## 5. 🔎 Data Filtering

Filtering data based on conditions.

In [26]:
# Simple condition
print("Employees with salary > 7000:")
print(df[df['salary'] > 7000])

Employees with salary > 7000:
     name  age  salary department  experience
1    Ayse   30    7500         HR           5
2  Mehmet   35    9000         IT          10
5  Zeynep   33    8000         HR           8

In [27]:
# Multiple conditions (&, |)
print("IT department AND salary > 5000:")
mask = (df['department'] == 'IT') & (df['salary'] > 5000)
print(df[mask])

IT department AND salary > 5000:
     name  age  salary department  experience
2  Mehmet   35    9000         IT          10
7   Merve   29    7000         IT           6

In [28]:
# isin() - filter by a list of values
print("IT or Finance department:")
print(df[df['department'].isin(['IT', 'Finance'])])

IT or Finance department:
     name  age  salary department  experience
0     Ali   25    5000         IT           2
2  Mehmet   35    9000         IT          10
3   Fatma   28    6500    Finance           4
4     Can   22    4500         IT           1
6   Hasan   27    5500    Finance           3
7   Merve   29    7000         IT           6

In [ ]:
# str.contains() - filter rows containing text
print("Names containing 'a' or 'A':")
print(df[df['name'].str.contains('a', case=False)])

In [ ]:
# between() - range filter
print("Age between 25 and 30:")
print(df[df['age'].between(25, 30)])

---
## 6. 🧹 Data Cleaning

Handling missing values, duplicates, and reshaping data.

In [32]:
# DataFrame with missing values
df_missing = pd.DataFrame({
    'name': ['Alice', 'Bob', None, 'Diana', 'Eve'],
    'age': [25, None, 35, 28, None],
    'score': [85.0, 92.0, None, 95.0, 88.0]
})
print("DataFrame with missing values:")
print(df_missing)
print("\nMissing value count:")
print(df_missing.isnull().sum())

DataFrame with missing values:
    name   age  score
0  Alice  25.0   85.0
1    Bob   NaN   92.0
2   None  35.0    NaN
3  Diana  28.0   95.0
4    Eve   NaN   88.0

Missing value count:
name     1
age      2
score    1
dtype: int64

In [33]:
# isna() and notna()
print("Which cells are empty?")
print(df_missing.isna())

Which cells are empty?
    name    age  score
0  False  False  False
1  False   True  False
2   True  False   True
3  False  False  False
4  False   True  False

In [34]:
# dropna() - remove rows with missing values
print("Drop all missing rows (dropna):")
print(df_missing.dropna())

print("\nDrop rows missing only in 'name':")
print(df_missing.dropna(subset=['name']))

Drop all missing rows (dropna):
    name   age  score
0  Alice  25.0   85.0
3  Diana  28.0   95.0

Drop rows missing only in 'name':
    name   age  score
0  Alice  25.0   85.0
1    Bob   NaN   92.0
3  Diana  28.0   95.0
4    Eve   NaN   88.0

In [35]:
# fillna() - fill missing values
print("Fill numeric missing values with mean/median:")
df_filled = df_missing.copy()
df_filled['age'] = df_filled['age'].fillna(df_filled['age'].mean())
df_filled['score'] = df_filled['score'].fillna(df_filled['score'].median())
df_filled['name'] = df_filled['name'].fillna('Unknown')
print(df_filled)

Fill numeric missing values with mean/median:
      name        age  score
0    Alice  25.000000   85.0
1      Bob  29.333333   92.0
2  Unknown  35.000000   90.0
3    Diana  28.000000   95.0
4      Eve  29.333333   88.0

In [36]:
# Duplicates
df_dup = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Alice', 'Charlie', 'Bob'],
    'score': [85, 90, 85, 75, 90]
})
print("Original:")
print(df_dup)
print("\nDuplicate rows:")
print(df_dup.duplicated())
print("\nAfter removing duplicates:")
print(df_dup.drop_duplicates())

Original:
      name  score
0    Alice     85
1      Bob     90
2    Alice     85
3  Charlie     75
4      Bob     90

Duplicate rows:
0    False
1    False
2     True
3    False
4     True
dtype: bool

After removing duplicates:
      name  score
0    Alice     85
1      Bob     90
3  Charlie     75

In [37]:
# rename() - rename columns
df_renamed = df[['name', 'salary', 'age']].copy()
df_renamed = df_renamed.rename(columns={'name': 'full_name', 'salary': 'annual_salary', 'age': 'years_old'})
print("Renamed columns:")
print(df_renamed.head())

Renamed columns:
  full_name  annual_salary  years_old
0       Ali           5000         25
1      Ayse           7500         30
2    Mehmet           9000         35
3     Fatma           6500         28
4       Can           4500         22

---
## 7. 🔄 Data Transformation

Processing and transforming data.

In [38]:
df2 = df.copy()

def classify_salary(salary):
    if salary < 5500:
        return 'Low'
    elif salary < 7500:
        return 'Medium'
    else:
        return 'High'

df2['salary_level'] = df2['salary'].apply(classify_salary)
print("Salary level classification:")
print(df2[['name', 'salary', 'salary_level']])

Salary level classification:
     name  salary salary_level
0     Ali    5000          Low
1    Ayse    7500         High
2  Mehmet    9000         High
3   Fatma    6500       Medium
4     Can    4500          Low
5  Zeynep    8000         High
6   Hasan    5500       Medium
7   Merve    7000       Medium

In [39]:
# map() - map values in a Series
dept_map = {'IT': 'Information Technology', 'HR': 'Human Resources', 'Finance': 'Financial Affairs'}
df2['department_full'] = df2['department'].map(dept_map)
print("Full department names (map):")
print(df2[['name', 'department', 'department_full']])

Full department names (map):
     name department         department_full
0     Ali         IT  Information Technology
1    Ayse         HR         Human Resources
2  Mehmet         IT  Information Technology
3   Fatma    Finance       Financial Affairs
4     Can         IT  Information Technology
5  Zeynep         HR         Human Resources
6   Hasan    Finance       Financial Affairs
7   Merve         IT  Information Technology

In [41]:
# sort_values() - sorting
print("Sort by salary descending:")
print(df.sort_values('salary', ascending=False))

print("\nSort by department ascending, salary descending:")
print(df.sort_values(['department', 'salary'], ascending=[True, False]))

Sort by salary descending:
     name  age  salary department  experience
2  Mehmet   35    9000         IT          10
5  Zeynep   33    8000         HR           8
1    Ayse   30    7500         HR           5
7   Merve   29    7000         IT           6
3   Fatma   28    6500    Finance           4
6   Hasan   27    5500    Finance           3
0     Ali   25    5000         IT           2
4     Can   22    4500         IT           1

Sort by department ascending, salary descending:
     name  age  salary department  experience
3   Fatma   28    6500    Finance           4
6   Hasan   27    5500    Finance           3
5  Zeynep   33    8000         HR           8
1    Ayse   30    7500         HR           5
2  Mehmet   35    9000         IT          10
7   Merve   29    7000         IT           6
0     Ali   25    5000         IT           2
4     Can   22    4500         IT           1

In [43]:
# astype() - convert data types
print(f"Before - age dtype: {df['age'].dtype}")
df3 = df.copy()
df3['age'] = df3['age'].astype(float)
print(f"After  - age dtype: {df3['age'].dtype}")

# Categorical type
df3['department'] = df3['department'].astype('category')
print(f"Categories: {df3['department'].cat.categories.tolist()}")

Before - age dtype: int64
After  - age dtype: float64
Categories: ['Finance', 'HR', 'IT']

In [44]:
df3

     name   age  salary department  experience
0     Ali  25.0    5000         IT           2
1    Ayse  30.0    7500         HR           5
2  Mehmet  35.0    9000         IT          10
3   Fatma  28.0    6500    Finance           4
4     Can  22.0    4500         IT           1
5  Zeynep  33.0    8000         HR           8
6   Hasan  27.0    5500    Finance           3
7   Merve  29.0    7000         IT           6

In [ ]:
# cut() and qcut() - bin numeric data into groups
df3['age_group'] = pd.cut(df3['age'],
                          bins=[0, 25, 30, 100],
                          labels=['Young (≤25)', 'Mid (26-30)', 'Senior (>30)'])
print("Age groups (cut):")
print(df3[['name', 'age', 'age_group']])

---
## 8. 📦 Grouping & Aggregation

Analyzing data by categories using `groupby()`.

In [47]:
# Basic groupby
print("Average salary by department:")
print(df.groupby('department')['salary'].median())

Average salary by department:
department
Finance    6000.0
HR         7750.0
IT         6000.0
Name: salary, dtype: float64

In [49]:
# Multiple aggregations - agg()
print("Salary statistics by department:")
print(df.groupby('department')['salary'].agg(['min', 'max', 'mean', 'count']))

Salary statistics by department:
             min   max    mean  count
department
Finance     5500  6500  6000.0      2
HR          7500  8000  7750.0      2
IT          4500  9000  6375.0      4

In [50]:
# Different aggregations for multiple columns
print("Detailed aggregation:")
result = df.groupby('department').agg(
    avg_salary=('salary', 'mean'),
    total_salary=('salary', 'sum'),
    headcount=('name', 'count'),
    avg_experience=('experience', 'mean')
).round(1)
print(result)

Detailed aggregation:
            avg_salary  total_salary  headcount  avg_experience
department
Finance         6000.0         12000          2             3.5
HR              7750.0         15500          2             6.5
IT              6375.0         25500          4             4.8

In [ ]:
# transform() - add group-level value back to original DataFrame
df4 = df.copy()
df4['dept_avg_salary'] = df4.groupby('department')['salary'].transform('mean')
df4['salary_diff'] = df4['salary'] - df4['dept_avg_salary']
print("Salary difference from department average:")
print(df4[['name', 'department', 'salary', 'dept_avg_salary', 'salary_diff']].round(1))

---
## 9. 🔗 Joining & Merging

Combining DataFrames.

In [52]:
# Sample DataFrames
df_employees = pd.DataFrame({
    'id': [1, 2, 3, 4, 5],
    'name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Eve'],
    'dept_id': [10, 20, 10, 30, 50]
})

df_departments = pd.DataFrame({
    'dept_id': [10, 20, 30, 40],
    'dept_name': ['IT', 'HR', 'Finance', 'Marketing'],
    'location': ['New York', 'Chicago', 'Boston', 'Seattle']
})

print("Employees:")
print(df_employees)
print("\nDepartments:")
print(df_departments)

Employees:
   id     name  dept_id
0   1    Alice       10
1   2      Bob       20
2   3  Charlie       10
3   4    Diana       30
4   5      Eve       50

Departments:
   dept_id  dept_name  location
0       10         IT  New York
1       20         HR   Chicago
2       30    Finance    Boston
3       40  Marketing   Seattle

In [53]:
# merge() - SQL-style JOIN
print("Inner Join (default):")
print(pd.merge(df_employees, df_departments, on='dept_id'))

print("\nLeft Join (all employees):")
print(pd.merge(df_employees, df_departments, on='dept_id', how='left'))

print("\nRight Join (all departments):")
print(pd.merge(df_employees, df_departments, on='dept_id', how='right'))

Inner Join (default):
   id     name  dept_id dept_name  location
0   1    Alice       10        IT  New York
1   3  Charlie       10        IT  New York
2   2      Bob       20        HR   Chicago
3   4    Diana       30   Finance    Boston

Left Join (all employees):
   id     name  dept_id dept_name  location
0   1    Alice       10        IT  New York
1   2      Bob       20        HR   Chicago
2   3  Charlie       10        IT  New York
3   4    Diana       30   Finance    Boston
4   5      Eve       50       NaN       NaN

Right Join (all departments):
    id     name  dept_id  dept_name  location
0  1.0    Alice       10         IT  New York
1  3.0  Charlie       10         IT  New York
2  2.0      Bob       20         HR   Chicago
3  4.0    Diana       30    Finance    Boston
4  NaN      NaN       40  Marketing   Seattle

In [55]:
# concat() - stack DataFrames vertically or horizontally
df_a = pd.DataFrame({'name': ['Alice', 'Bob'], 'score': [85, 90]})
df_b = pd.DataFrame({'name': ['Charlie', 'Diana'], 'score': [78, 95]})
print(df_a)
print(df_b)
print("Vertical concat:")
print(pd.concat([df_a, df_b], ignore_index=True))

    name  score
0  Alice     85
1    Bob     90
      name  score
0  Charlie     78
1    Diana     95
Vertical concat:
      name  score
0    Alice     85
1      Bob     90
2  Charlie     78
3    Diana     95

---
## 12. ✍️ String Operations

Working with text data using the `.str` accessor.

In [ ]:
names = pd.Series(['  alice smith  ', 'BOB JONES', 'charlie brown', 'DiAnA PrInCe'])

print("Original:")
print(names.tolist())

print("\nUppercase (upper):")
print(names.str.upper().tolist())

print("\nLowercase (lower):")
print(names.str.lower().tolist())

print("\nTitle case (title):")
print(names.str.strip().str.title().tolist())

print("\nStrip whitespace (strip):")
print(names.str.strip().tolist())

In [ ]:
# split, replace, len
full_names = pd.Series(['Alice Smith', 'Bob Jones', 'Charlie Brown'])

print("Split first and last name:")
split_names = full_names.str.split(' ', expand=True)
split_names.columns = ['first_name', 'last_name']
print(split_names)

print("\nCharacter count:")
print(full_names.str.len().tolist())

---
## 13. 📤 Reading & Writing Data

Saving and loading files.

In [ ]:
# Save and read CSV
df.to_csv('employees.csv', index=False)
df_read = pd.read_csv('employees.csv')
print("CSV saved and read back:")
print(df_read.head())

# Excel (requires openpyxl)
# df.to_excel('employees.xlsx', index=False)

# JSON
df.to_json('employees.json', orient='records', indent=2)
df_json = pd.read_json('employees.json')
print("\nRead from JSON:")
print(df_json.head())

---
---
# 🎓 EXERCISES

> Try to solve the questions below. Answers are provided in the next section.

First, run the cell below to load the dataset:

In [57]:
# ===== Dataset for Exercises =====
import pandas as pd
import numpy as np
np.random.seed(99)
df_market = pd.DataFrame({
    'order_id': range(1, 51),
    'customer': np.random.choice(['Alice', 'Bob', 'Carol', 'David', 'Eve'], 50),
    'product': np.random.choice(['Apple', 'Banana', 'Orange', 'Strawberry', 'Pear'], 50),
    'category': np.random.choice(['Fruit A', 'Fruit B'], 50),
    'quantity': np.random.randint(1, 20, 50),
    'unit_price': np.random.choice([2.5, 3.0, 4.5, 6.0, 5.5], 50),
    'date': pd.date_range('2024-01-01', periods=50, freq='7D')
})
df_market.loc[[3, 12, 25, 38], 'quantity'] = np.nan
df_market.loc[[7, 19, 41], 'unit_price'] = np.nan
df_market['total_price'] = df_market['quantity'] * df_market['unit_price']
print("Market dataset:")
print(df_market.head(10))
print(f"\nShape: {df_market.shape}")

Market dataset:
   order_id customer     product category  quantity  unit_price       date  \
0         1      Bob  Strawberry  Fruit B       7.0         4.5 2024-01-01
1         2    David      Banana  Fruit A      16.0         6.0 2024-01-08
2         3      Bob        Pear  Fruit A       4.0         2.5 2024-01-15
3         4    Alice        Pear  Fruit A       NaN         4.5 2024-01-22
4         5      Bob  Strawberry  Fruit B       7.0         4.5 2024-01-29
5         6    Alice       Apple  Fruit A       8.0         3.0 2024-02-05
6         7    Carol       Apple  Fruit A      10.0         5.5 2024-02-12
7         8      Eve      Banana  Fruit B       3.0         NaN 2024-02-19
8         9      Eve      Orange  Fruit A       8.0         6.0 2024-02-26
9        10      Bob      Banana  Fruit A       6.0         4.5 2024-03-04

   total_price
0         31.5
1         96.0
2         10.0
3          NaN
4         31.5
5         24.0
6         55.0
7          NaN
8         48.0
9         27.0

Shape: (50, 8)

### ❓ Question 1
Find the **total number of missing values** in the dataset and identify **which columns** contain them.

In [61]:
# Write your solution here
print(df_market.isnull().sum())
print(df_market.isnull().sum()/len(df_market)*100)

order_id       0
customer       0
product        0
category       0
quantity       4
unit_price     3
date           0
total_price    7
dtype: int64
order_id        0.0
customer        0.0
product         0.0
category        0.0
quantity        8.0
unit_price      6.0
date            0.0
total_price    14.0
dtype: float64

### ❓ Question 2
Fill missing values in `quantity` with the **mean** and in `unit_price` with the **median**. Then recalculate the `total_price` column.

In [65]:
# Write your solution here
df_market2=df_market.copy()
q_mean=df_market2['quantity'].mean()
df_market2['quantity']=df_market2['quantity'].fillna(q_mean)

medyan_up=df_market2['unit_price'].median()
df_market2['unit_price']=df_market2['unit_price'].fillna(medyan_up)

df_market2['total_price']=df_market2['quantity']*df_market2['unit_price']

df_market2.head(10)

,order_id,customer,product,category,quantity,unit_price,date,total_price
0,1,Bob,Strawberry,Fruit B,7.0,4.5,2024-01-01,31.50
1,2,David,Banana,Fruit A,16.0,6.0,2024-01-08,96.00
2,3,Bob,Pear,Fruit A,4.0,2.5,2024-01-15,10.00
3,4,Alice,Pear,Fruit A,9.5,4.5,2024-01-22,42.75
4,5,Bob,Strawberry,Fruit B,7.0,4.5,2024-01-29,31.50
5,6,Alice,Apple,Fruit A,8.0,3.0,2024-02-05,24.00
6,7,Carol,Apple,Fruit A,10.0,5.5,2024-02-12,55.00
7,8,Eve,Banana,Fruit B,3.0,4.5,2024-02-19,13.50
8,9,Eve,Orange,Fruit A,8.0,6.0,2024-02-26,48.00
9,10,Bob,Banana,Fruit A,6.0,4.5,2024-03-04,27.00

### ❓ Question 3
Show each **customer's** total spending, sorted from highest to lowest.

In [ ]:
# Write your solution here

### ❓ Question 4
For each **product**, calculate: total quantity sold, average unit price, and total revenue.

In [ ]:
# Write your solution here

### ❓ Question 5
Filter orders where `total_price` **exceeds 100** and show which customers placed those orders.

In [ ]:
# Write your solution here

### ❓ Question 6
Add a `'discount'` column using this rule: if `total_price > 100` → `10%`, if `total_price > 50` → `5%`, otherwise `0%`.

In [ ]:
# Write your solution here

### ❓ Question 7
Group the data by **month** to calculate monthly total revenue and find the **best-performing month**.

In [ ]:
# Write your solution here

### ❓ Question 8
Convert customer names to uppercase and append the suffix `'_CUSTOMER'`. Store the result in a new column called `'customer_code'`.

In [ ]:
# Write your solution here

---
---
# ✅ ANSWERS

### ✅ Answer 1 - Missing Value Analysis

In [ ]:
print("Missing values per column:")
print(df_market.isnull().sum())

print(f"\nTotal missing values: {df_market.isnull().sum().sum()}")

print("\nMissing value percentage:")
print((df_market.isnull().sum() / len(df_market) * 100).round(1))

### ✅ Answer 2 - Filling Missing Values

In [ ]:
df_clean = df_market.copy()

# quantity -> fill with mean
mean_qty = df_clean['quantity'].mean()
df_clean['quantity'] = df_clean['quantity'].fillna(mean_qty)

# unit_price -> fill with median
median_price = df_clean['unit_price'].median()
df_clean['unit_price'] = df_clean['unit_price'].fillna(median_price)

# Recalculate total_price
df_clean['total_price'] = df_clean['quantity'] * df_clean['unit_price']

print(f"Missing values after filling: {df_clean.isnull().sum().sum()}")
print(f"Mean quantity: {mean_qty:.2f}, Median unit price: {median_price:.2f}")
print("\nFirst 10 rows:")
print(df_clean.head(10))

### ✅ Answer 3 - Customer Total Spending

In [ ]:
customer_spending = (
    df_clean
    .groupby('customer')['total_price']
    .sum()
    .sort_values(ascending=False)
    .round(2)
)
print("Customer total spending (highest to lowest):")
print(customer_spending.to_string())
print(f"\nTop spender: {customer_spending.idxmax()} (${customer_spending.max():.2f})")

### ✅ Answer 4 - Product Analysis

In [ ]:
product_analysis = df_clean.groupby('product').agg(
    total_quantity=('quantity', 'sum'),
    avg_unit_price=('unit_price', 'mean'),
    total_revenue=('total_price', 'sum')
).round(2)

print("Product analysis:")
print(product_analysis)
print(f"\nBest-selling product: {product_analysis['total_quantity'].idxmax()}")
print(f"Highest revenue product: {product_analysis['total_revenue'].idxmax()}")

### ✅ Answer 5 - Filtering

In [ ]:
high_orders = df_clean[df_clean['total_price'] > 100]

print(f"Orders over $100: {len(high_orders)}")
print("\nThese orders:")
print(high_orders[['order_id', 'customer', 'product', 'quantity', 'total_price']].to_string(index=False))

print("\nCustomer breakdown:")
print(high_orders['customer'].value_counts())

### ✅ Answer 6 - Discount Column

In [ ]:
def calculate_discount(total):
    if total > 100:
        return 0.10  # 10%
    elif total > 50:
        return 0.05  # 5%
    else:
        return 0.00  # 0%

df_clean['discount'] = df_clean['total_price'].apply(calculate_discount)
df_clean['discounted_price'] = df_clean['total_price'] * (1 - df_clean['discount'])

print("Discounts applied:")
print(df_clean[['order_id', 'customer', 'total_price', 'discount', 'discounted_price']].head(15).to_string(index=False))

print("\nDiscount distribution:")
print(df_clean['discount'].value_counts().sort_index())

### ✅ Answer 7 - Monthly Revenue

In [ ]:
df_clean['month'] = df_clean['date'].dt.month
df_clean['month_name'] = df_clean['date'].dt.strftime('%B')

monthly_revenue = (
    df_clean.groupby(['month', 'month_name'])['total_price']
    .sum()
    .round(2)
    .reset_index()
    .sort_values('month')
)

print("Monthly total revenue:")
print(monthly_revenue[['month_name', 'total_price']].to_string(index=False))

best_idx = monthly_revenue['total_price'].idxmax()
best_month = monthly_revenue.loc[best_idx]
print(f"\nBest month: {best_month['month_name']} (${best_month['total_price']:.2f})")

### ✅ Answer 8 - String Operations

In [ ]:
df_clean['customer_code'] = df_clean['customer'].str.upper() + '_CUSTOMER'

print("Customer codes:")
print(df_clean[['customer', 'customer_code']].drop_duplicates().reset_index(drop=True))

---
## 🏆 Congratulations!

You've completed this notebook. Here's a summary of what you've learned:

| Topic | Methods |
|-------|---------|
| Data structures | `Series`, `DataFrame` |
| Exploration | `head()`, `tail()`, `info()`, `describe()`, `shape` |
| Selection | `loc`, `iloc`, `at`, `iat` |
| Filtering | Boolean mask, `isin()`, `query()`, `between()` |
| Cleaning | `dropna()`, `fillna()`, `drop_duplicates()` |
| Transformation | `apply()`, `map()`, `sort_values()`, `astype()` |
| Grouping | `groupby()`, `agg()`, `transform()` |
| Merging | `merge()`, `concat()` |
| Time series | `date_range()`, `resample()`, `rolling()` |
| Strings | `.str.upper()`, `.str.split()`, `.str.contains()` |

### 📚 Next Steps
- [Official Pandas Documentation](https://pandas.pydata.org/docs/)
- Data visualization with Matplotlib / Seaborn
- Machine learning with Scikit-learn